### ISSUE TITLE
Manasteel tools causes internal server error upon use.

### ISSUE THREAD

**Issue by Phenolphthalein** [wendall911/TCIntegrations#15]
[latest.log](https://github.com/wendall911/TCIntegrations/files/9127365/latest.log)

[17Jul2022 17:33:35.794] [Server thread/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[17Jul2022 17:33:35.876] [Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /25.57.95.239:51789
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.54.jar%2316!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at tcintegrations.items.tool.modifiers.ManaItemModifier.getManaPerDamage(ManaItemModifier.java:20) ~[TCIntegrations-1.18.2-2.0.4.0.jar%23155!/:task ':jar' property 'archiveVersion']
	at tcintegrations.items.tool.modifiers.ManaItemModifier.onInventoryTick(ManaItemModifier.java:29) ~[TCIntegrations-1.18.2-2.0.4.0.jar%23155!/:task ':jar' property 'archiveVersion']
	at slimeknights.tconstruct.library.tools.item.ModifiableItem.m_6883_(ModifiableItem.java:341) ~[TConstruct-1.18.2-3.5.1.31.jar%23156!/:1.18.2-3.5.1.31]
	at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:494) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:229) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:490) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?]
	... 9 more
[17Jul2022 17:33:35.892] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: PenguinsGoWild lost connection: Internal server error
[17Jul2022 17:33:35.892] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: PenguinsGoWild left the game

Crafting and having the item inside the inventory is stable. Single player is stable. In multiplayer however, upon depleting durability, immediately causes internal server error and player gets kicked. Server still functions and other players are okay, only the player with the tool cannot join back unless tool is removed from inventory via external means. Happens every time a tool with the mana attribute is used.

**Comment by wendall911** [comment]
Very sorry about this! I will get a build out shortly to address this.
